M48
; DRILL file {KiCad 9.0.6} date 2026-04-24T20:54:10+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-24T20:54:10+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.850
%
G90
G05
T1
X133.61Y-144.887
X139.39Y-144.887
T2
X148.0Y-121.0
X148.0Y-130.0
M30
